name: Terraform AWS Manual Integration

on:
  workflow_dispatch:

jobs:
  terraform-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0  # Change as needed

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # Uncomment the following to enable apply step
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve 

permissions:
  id-token: write
  contents: read 